package com.codeatlas.core.decision;

public enum DecisionKind {
    IF_CONDITION,
    IF_ELSE_CONDITION,
    IF_ELSE_IF_CHAIN,
    EARLY_RETURN,
    CONDITIONAL_THROW,
    SWITCH_DECISION,
    SWITCH_EXPRESSION_DECISION,
    SWITCH_CASE,
    TERNARY_CONDITION,
    OPTIONAL_BRANCH,
    STREAM_FILTER,
    UNKNOWN_CONDITION
}
